on_worker_boot do
  # Valid on Rails 4.1+ using the `config/database.yml` method of setting `pool` size
  ActiveRecord::Base.establish_connection
end

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Red_Sweater_development

test:
  <<: *default
  database: Red_Sweater_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: Red_Sweater_production
  adapter: postgresql
  username: Red_Sweater
  password:
