default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Red_Sweater_development

test:
  <<: *default
  database: Red_Sweater_test

production:
  <<: *default
  database: Red_Sweater_production
  username: Red_Sweater
  password: <%= ENV['RED_SWEATER_DATABASE_PASSWORD'] %>
